name: CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      TEST_SUITE:
        description: 'Select the test suite to run'
        required: true
        default: 'admin_portal_sanity.py'
        type: choice
        options:
          - 'admin_portal_sanity.py'
          - 'service_portal_sanity.py'
          - 'sanity_for_different_function.py'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: 'feature'

    - name: Install dependencies
      run: |
        if ! command -v python3 &> /dev/null; then
            echo "Python3 is not installed. Please install Python3."
            exit 1
        fi

        python3 -m venv venv

        source venv/bin/activate
        pip install --upgrade pip
        pip install pytest pytest-playwright pyyaml selenium pyautogui
        playwright install

    - name: Debug DNS Resolution
      run: |
        nslookup revamp-qa-console.yntraa.com
        ping -c 4 revamp-qa-console.yntraa.com

    - name: Wait for network stabilization
      run: sleep 30

    - name: Run Tests
      run: |
        source venv/bin/activate
        pytest --browser=chromium smoke_testing/${{ github.event.inputs.TEST_SUITE }} --junitxml=report.xml

    - name: Archive Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: report.xml

    - name: Parse Logs
      run: |
        python parse_log.py
      if: always()

    - name: Upload Logs
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: '**/*.log'
