name: Python application

on:
 push:
   branches:
     - feature
 pull_request:
   branches:
     - feature

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install playwright
        playwright install

    - name: Run tests
      run: |
        pytest --browser=chromium smoke_testing/sanity_for_different_function.py

