name: CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      TEST_SUITE:
        description: 'Select the test suite to run'
        required: true
        default: 'admin_portal_sanity.py'
        type: choice
        options:
          - 'admin_portal_sanity.py'
          - 'service_portal_sanity.py'
          - 'sanity_for_different_function.py'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: 'feature'

    - name: Install dependencies
      run: |
        # Check if Python3 is installed
        if ! command -v python3 &> /dev/null; then
            echo "Python3 is not installed. Please install Python3."
            exit 1
        fi

        # Create virtual environment
        python3 -m venv venv

        # Activate virtual environment and install dependencies
        source venv/bin/activate
        pip install --upgrade pip
        pip install pytest pytest-playwright pyyaml selenium pyautogui
        playwright install

    - name: Run Tests
      run: |
        source venv/bin/activate
        pytest --browser=chromium --junitxml=results.xml smoke_testing/${{ github.event.inputs.TEST_SUITE }}

    - name: Send email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.example.com
        server_port: 587
        username: atul@coredge.io
        password: Rakuten@1234
        subject: "Test Email from GitHub Actions"
        to: "recipient@example.com"
        from: "atul@coredge.io"
        body: "This is a test email sent from GitHub Actions."
