name: CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      TEST_FILE:
        description: 'Select the test file to run'
        required: true
        default: 'admin_portal_sanity.py'
        type: choice
        options:
          - 'admin_portal_sanity.py'
          - 'service_portal_sanity.py'
          - 'sanity_for_different_function.py'
      BRANCH:
        description: 'Select the branch to run the tests on'
        required: true
        default: 'feature'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.BRANCH }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip  # Ensure pip is up-to-date
        pip install -r requirements.txt

    - name: Install browser dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        pip install pytest-playwright
        playwright install

    - name: Run selected test file
      run: |
        source venv/bin/activate
        pytest --junitxml=results.xml smoke_testing/${{ github.event.inputs.TEST_FILE }}

    - name: Publish Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: results.xml

    - name: Send Email with Test Results
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.example.com
        server_port: 587
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: "CI Test Results - Build #${{ github.run_number }}"
        to: atul@coredge.io
        from: no-reply@example.com
        body: |
          Please find the attached test results.

          Total Tests: ${{ steps.get-test-count.outputs.total }}
          Passed Tests: ${{ steps.get-test-count.outputs.passed }}
          Failed Tests: ${{ steps.get-test-count.outputs.failed }}
        attachments: results.xml

  get-test-count:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Parse JUnit results
      id: get-test-count
      run: |
        TOTAL=$(grep -o 'testsuite tests="[0-9]*"' results.xml | grep -o '[0-9]*')
        PASSED=$(grep -o 'testsuite tests="[0-9]*" errors="0" failures="0"' results.xml | grep -o '[0-9]*')
        FAILED=$((TOTAL - PASSED))
        echo "::set-output name=total::$TOTAL"
        echo "::set-output name=passed::$PASSED"
        echo "::set-output name=failed::$FAILED"
