name: CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      TEST_SUITE:
        description: 'Select the test suite to run'
        required: true
        default: 'admin_portal_sanity.py'
        type: choice
        options:
          - 'admin_portal_sanity.py'
          - 'service_portal_sanity.py'
          - 'sanity_for_different_function.py'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: 'feature'

      - name: Install dependencies
        run: |
          # Check if Python3 is installed
          if ! command -v python3 &> /dev/null; then
              echo "Python3 is not installed. Please install Python3."
              exit 1
          fi

          # Create virtual environment
          python3 -m venv venv

          # Activate virtual environment and install dependencies
          source venv/bin/activate
          pip install --upgrade pip
          pip install pytest pytest-playwright pyyaml selenium pyautogui
          playwright install

      - name: Run Tests and Parse Logs
        run: |
          source venv/bin/activate
          if [ $? -ne 0 ]; then
            echo "Failed to activate virtual environment"
            exit 1
          fi
          
          pytest --browser=chromium smoke_testing/sanity_for_different_function.py > pytest_output.txt
          if [ $? -ne 0 ]; then
            echo "Failed to run pytest command"
            exit 1
          fi
          
          python parse_log.py
          if [ $? -ne 0 ]; then
            echo "Failed to run parse_log.py command"
            exit 1
          fi
        shell: /bin/bash
