name: CI Pipeline

on:
  push:
    branches:
      - feature
  pull_request:
    branches:
      - feature

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        repository: coredgeio/yntraa_test_automation
        ref: feature

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install pytest pytest-playwright pyyaml selenium pyautogui
        playwright install

    - name: Run Tests
      run: |
        source venv/bin/activate
        pytest --browser=chromium --junitxml=results.xml smoke_testing/${{ github.event.inputs.TEST_SUITE }}
      env:
        TEST_SUITE: ${{ github.event.inputs.TEST_SUITE }}

    - name: Archive Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: yntraa_test_automation/results.xml

    - name: Parse Test Results
      if: always()
      id: parse_results
      run: |
        total=$(xmllint --xpath 'string(count(//testcase))' yntraa_test_automation/results.xml)
        failed=$(xmllint --xpath 'string(count(//testcase[failure]))' yntraa_test_automation/results.xml)
        passed=$((total - failed))
        echo "::set-output name=total::$total"
        echo "::set-output name=passed::$passed"
        echo "::set-output name=failed::$failed"

    - name: Send Email
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.example.com
        server_port: 587
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: "Sanity Result for Service portal"
        body: |
          Total Tests: ${{ steps.parse_results.outputs.total }}
          Passed: ${{ steps.parse_results.outputs.passed }}
          Failed: ${{ steps.parse_results.outputs.failed }}
        to: atul@coredge.io
        from: you@example.com
