name: CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      TEST_SUITE:
        description: 'Select the test suite to run'
        required: true
        default: 'admin_portal_sanity.py'
        type: choice
        options:
          - 'admin_portal_sanity.py'
          - 'service_portal_sanity.py'
          - 'sanity_for_different_function.py'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: 'feature'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-playwright pyyaml selenium pyautogui
        playwright install

    - name: Run Tests
      run: |
        pytest --browser=chromium --junitxml=results.xml smoke_testing/${{ github.event.inputs.TEST_SUITE }}

    - name: Archive Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: results.xml

    - name: Parse Test Results
      id: parse-results
      run: |
        TOTAL=$(grep -o 'tests="[0-9]*"' results.xml | grep -o '[0-9]*')
        FAILED=$(grep -o 'failure message=' results.xml | wc -l)
        PASSED=$((TOTAL - FAILED))
        echo "total=$TOTAL" >> $GITHUB_ENV
        echo "failed=$FAILED" >> $GITHUB_ENV
        echo "passed=$PASSED" >> $GITHUB_ENV

    - name: Send Email with Test Results
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{ secrets.SMTP_SERVER }}
        server_port: ${{ secrets.SMTP_PORT }}
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: "Sanity Result for Yntraa"
        to: 'atul@coredge.io'
        from: 'atul@coredge.io'
        body: |
          Total Tests: ${{ env.total }}
          Passed Tests: ${{ env.passed }}
          Failed Tests: ${{ env.failed }}
          {% if env.failed == 0 %}
          All tests passed successfully.
          {% else %}
          Some tests failed. See attached results for details.
          {% endif %}
        attachments: results.xml

    - name: Upload Logs
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: '**/*.log'
